### ISSUE TITLE
Balance 0 in explorer

### ISSUE THREAD

**Issue by danangelf** [lAmeR1/kaspa-explorer#16]
in explorer it shows balance 0 but in wallet not 0. txhash doesn't show wallet addrees and its hard to understand.

**Comment by lAmeR1** [comment]
Hello, you probably have a HDWallet, which changes the addresses. Are you sure you are requesting the correct address?

**Comment by danangelf** [comment]
I use Kaspa Web Wallet

**Comment by danangelf** [comment]
I use Kaspa Web Wallet

**Comment by lAmeR1** [comment]
Please go to debug -> show UTXOs .. there you have the correct Tx-Id and your wallet address
