### ISSUE TITLE
KDX wont connect to database

### ISSUE THREAD

**Issue by Hyporen** [lAmeR1/kaspa-explorer#37]
![Screenshot 2023-07-02 073435](https://github.com/lAmeR1/kaspa-explorer/assets/138375222/c5b648c5-b147-43b7-9f54-796ede3b02b7)
![Screenshot 2023-07-02 074049](https://github.com/lAmeR1/kaspa-explorer/assets/138375222/54e26071-0aea-41b4-984f-786a99ff8916)
![Screenshot 2023-07-02 074542](https://github.com/lAmeR1/kaspa-explorer/assets/138375222/9fe5ec40-89d9-4a10-beef-57f49864ed56)

**Comment by lAmeR1** [comment]
This is not a Kaspa explorer related issue 😐
