### ISSUE TITLE
Пропали монеты с кошелька kaspa

### ISSUE THREAD

**Issue by Kaspuykrali** [lAmeR1/kaspa-explorer#43]
После восстановления доступа к кошельку по 12 словам. Монеты с кошелька исчезли. В кошельке показывает только входящую транзакцию, а исходящих нет. В kaspa explore видно что монеты перешли на другой адрес кошелька. Как вернуть украденные монеты?

**Comment by Aleoami** [comment]
Эксплорер написан отдельным человеком и не имеет ничего общего в веб-кошельком или с КДХ, смотря где там обнаружился неверный баланс. За помощью можно обратиться либо в дискорд Каспы discord.gg/kaspa, либо в русскую t.me/kaspa_rus или английскую t.me/kaspaenglish группу в Телеграме. В общем же вариантов всего два: либо сид-фраза была введена в поддельный кошелек по фишинговой ссылке, если ссылка была взята не с сайта Каспы и не через закладку в браузере, а через поиск в Гугле. В этом случае ничего сделать нельзя. Либо кошельком была самостоятельно произведена операция компаундинга UTXO, и тогда койны были сгруппированы и пересланы на адрес сдачи этого же кошелька, тогда имеет место просто ошибка отображения баланса. В этом случае можно очистить кэш браузера и ввести сид-фразу еще раз, либо ввести ее в другом браузере. Предварительно убедившись, что ссылка на веб-кошелек корректна: wallet.kaspanet.io. а не какой-нибудь kaspnet, не kaspawallet io и прочие похожие вариации скамеров.

**Comment by Kaspuykrali** [comment]
Спасибо.

**Comment by Kaspuykrali** [comment]
kaspa:qr73suu2kpsflgwt5q47h6m7esqm3xwmw2hxcyqajrqwruswlptm6wqanvzx4  есть адрес кошелька куда ушли монеты. Есть возможность как то обжаловать эти действия?
