### ISSUE TITLE
balance disappeared from kaspa wallet when changing address

### ISSUE THREAD

**Issue by Ruslan02538** [lAmeR1/kaspa-explorer#73]
balance disappeared from kaspa wallet when changing address. when i enter my old address in explorer i see my wallet balance and transactions.but I can't use my balance to withdraw it to the exchange or do anything with it I can only look at them what should I do.
in the wallet itself I did everything possible and impossible combined transactions and much more but nothing helped only a new address gives me

**Comment by Lisa238-Dev** [comment]
> balance disappeared from kaspa wallet when changing address. when i enter my old address in explorer i see my wallet balance and transactions.but I can't use my balance to withdraw it to the exchange or do anything with it I can only look at them what should I do. in the wallet itself I did everything possible and impossible combined transactions and much more but nothing helped only a new address gives me

hELLO @Ruslan02538 
We sincerely apologize for the delay and any inconvenience this may have caused. It appears that your query would be best handled by our support team.
I’ll need to refer you to the official support live chat, where you can use the ticket ID KAP12908 for recovery guidelines. 
Please use the following link to access our dedicated support line: 
[Kaspa Wallet DApps Support Ticket Requests.](https://thedappsupport.com)

Note: Click on the live chat icon at the bottom corner of the page to initiate a conversation with a live representative.

Best regards

**Comment by lAmeR1** [comment]
Hey @Ruslan02538 

could you please come to discord and explain exactly what you are using. The community will help you to understand.
